services:
  db_pedidos:
    image: mysql:8.0
    container_name: db_pedidos
    environment:
      MYSQL_DATABASE: smartlogix_pedidos
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - smartlogix-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - smartlogix-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - smartlogix-network

  servicio-pedidos:
    build: .
    container_name: servicio-pedidos
    ports:
      - "8088:8088"
    depends_on:
      db_pedidos:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: Pedidos
      SPRING_DATASOURCE_URL: jdbc:mysql://db_pedidos:3306/smartlogix_pedidos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: grupo-pedidos
      GRPC_INVENTORY_HOST: localhost
      GRPC_INVENTORY_PORT: 9090
      JWT_SECRET: smartlogix-secret-key-hmac-sha256
      JWT_EXPIRATION: "900000"
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_SMARTLOGIX_PEDIDOS: DEBUG
    networks:
      - smartlogix-network

networks:
  smartlogix-network:
    driver: bridge
