syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.smartlogix.inventario.grpc";

service ServicioInventario {
  // HU-INV-02: Consulta de stock
  rpc CheckStock (StockRequest) returns (StockResponse);
  
  // HU-INV-05: Reserva de stock (Síncrona)
  rpc ReserveStock (ReserveRequest) returns (ReserveResponse);
}

message StockRequest {
  string sku = 1;
}

message StockResponse {
  string sku = 1;
  int32 stock_total = 2;
  int32 stock_reservado = 3;
  int32 stock_disponible = 4;
  bool esta_disponible = 5;
}

message ReserveRequest {
  string sku = 1;
  int32 cantidad = 2;
}

message ReserveResponse {
  bool exito = 1;
  string mensaje = 2;
}